#include "Keyboard.h"
#include "DFRobot_ID809_I2C.h"
#include "string.h"
#include "Crypto.h"
#include "AES.h"
#include <EEPROM.h>
#define BAUD_RATE 57600
#define KRYPTON_AUTH "5d9f629d-faa4-452f"
#define DEVICE_ID "Pf4R;*#1"
#define ERROR "E"
#define DONE "D"
#define SUCCESS "S"
#define INFO "I"
#define PING "P"
#define PONG "PG"
#define GENERATE_PASSWORD "GRP"
#define TRANSMIT_PASSWORD "TXP"
#define RECIEVE_PASSWORD "RXP"
#define ADD_FINGERPRINT "ANFP"
#define COUNT_FINGERPRINTS "CFP"
#define DELETE_FINGERPRINT "DFP"
#define SMARTLINK_ADD "KEA"
#define GET_DEVICE_ID "KEG"
#define GET_SMART_LINK_PASSWORD "KEP"